<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.streamx.hub</groupId>
    <artifactId>libraries</artifactId>
    <version>1.0.2</version>
  </parent>

  <artifactId>data-model</artifactId>

  <properties>
    <jandex-maven-plugin.version>3.5.3</jandex-maven-plugin.version>
  </properties>

  <build>
    <plugins>
      <!-- Enable discovering @RegisterForReflection annotations on data model classes -->
      <plugin>
        <groupId>io.smallrye</groupId>
        <artifactId>jandex-maven-plugin</artifactId>
        <version>${jandex-maven-plugin.version}</version>
        <executions>
          <execution>
            <id>make-index</id>
            <goals>
              <goal>jandex</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>