quarkus.otel.traces.exporter=none

mp.messaging.incoming.resources.connector=quarkus-http
mp.messaging.incoming.resources.deserializer=com.streamx.reactive.messaging.http.CloudEventJsonDeserializer
mp.messaging.incoming.resources.path=/resources
mp.messaging.incoming.resources.protocolVersion=HTTP_2
mp.messaging.incoming.resources.twoPhaseResponseFlow=true

mp.messaging.outgoing.embed-events.connector=quarkus-http
mp.messaging.outgoing.embed-events.serializer=com.streamx.reactive.messaging.http.CloudEventJsonSerializer
mp.messaging.outgoing.embed-events.url=${STREAMX_ENDPOINT_EMBED_EVENTS}
mp.messaging.outgoing.embed-events.protocolVersion=HTTP_2
mp.messaging.outgoing.embed-events.twoPhaseResponseFlow=true


streamx.url-include-replacement-provider=SsiInclude

# --- OpenAI ---
quarkus.langchain4j.openai.api-key=${STREAMX_OPENAI_API_KEY}
quarkus.langchain4j.openai.chat-model.model-name=gpt-4o
quarkus.langchain4j.openai.chat-model.temperature=0.3
quarkus.langchain4j.openai.embedding-model.model-name=text-embedding-3-small

# --- pgvector Embedding Store ---
quarkus.langchain4j.pgvector.dimension=1536